### PR TITLE
fix param.sfo not found on linux systems

### PR DESCRIPTION
**Pull request by DistantThunder**
Path shenanigans

### CODE REVIEW

**Comment by AerialAirwaves** [comment]
Did the same trick after a short investigation, and only then looked into PRs and saw that the problem is solved already. I was about to open PR too.
I encountered the problem on OSX, - not a surprise because it uses PosixPath as Path too.
A myriad thanks for converter implementation to author, but.. I wonder, why he/she/.. still didn't merged it. 
It's quite minor compatibility bug, but it can make a problem for non-advanced *nix users like average mac / chrome os users for instance.

**Comment by DistantThunder** [comment]
Yeah  I probably need to make Posix behaviour the default and exclude for Windows instead. I was conservative in my approach because I didn't want to break something else.

**Comment by brandonforster** [comment]
Maybe this isn't the correct forum, but is it clear exactly what data param.sfo contains? Best I can tell, I didn't export a param.sfo file and my PS4 P5R clear save seems to work just fine (with all metadata, including clock) intact on PC.

**Comment by zarroboogs** [comment]
Thanks, merged 👍

~~Much delayed since I turned off notifications for this repo~~ 😔

As for the question in the most recent comment, param.sfo contains a save metadata string that's displayed in the load menu.
It's a leftover from PS4 where metadata can be viewed both in-game and in the save management system menu.
Clear saves are a special case where the metadata is ignored, IIRC.

**Pull request merged**
